name: detective_pikachu
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_native_splash: ^2.0.1+1
  http: ^0.13.3
  dio: ^4.0.0
  flutter_polyline_points: ^0.2.6
  google_maps_flutter: ^0.5.25
  geolocator: ^5.3.0
  provider: ^4.0.4
  url_launcher: ^5.4.2
  flutter_rating_bar: ^3.0.1+1
  bottom_drawer: ^0.0.5
  favorite_button: ^0.0.3
  badges: ^1.1.1
  carousel_slider: ^4.1.1
  dcdg: ^4.0.1

# Run commands to generate splash screen
# 1) flutter clean
# 2) flutter pub get
# 3) flutter pub run flutter_native_splash:create
flutter_native_splash:
    color: "#FEEB70" # yellow
    image: images/splash1.png

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - images/p.png
    - images/no.png
    - images/splash1.png
    - images/bread/cake.png
    - images/bread/cheese.png
    - images/bread/cream.png
    - images/bread/hot.png
    - images/bread/melon.png
    - images/bread/pie.png
    - images/bread/roll.png
    - images/seal/Bulbasaur.png
    - images/seal/Caterpie.png
    - images/seal/Charmander.png
    - images/seal/Diglett.png
    - images/seal/Doduo.png
    - images/seal/Eevee.png
    - images/seal/Gloom.png
    - images/seal/Magikarp.png
    - images/seal/Mewtwo.png
    - images/seal/Pikachu.png
    - images/seal/Rattata.png
    - images/seal/Slowbro.png
    - images/seal/Snorlax.png
    - images/seal/Squirtle.png


  # To add assets to your application, add an assets section, like this:

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages